version: 0.{build}-{branch}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- ps: nuget restore

build:
  verbosity: minimal
  
install:
  - cmd: git submodule -q update --init